### ISSUE TITLE
User story: show a curated list of policies that can be added

### ISSUE THREAD

**Issue by flavio** [kubewarden/ui#2]
> As a Rancher user,
> I would like to keep my clusters secure by enabling some Kubernetes policies.
> I would like to have a list of recommended policies to go through,
> so that I can get started quickly.

The goal is to have a page with a list of policies that we consider "a must" for our users.

Right now all our policies are available on [hub.kubewarden.io](https://hub.kubewarden.io), however we don't want the user to go through each policy.

Maybe we can add some metadata to the policies (like a `featured: true` attribute), that Rancher UI and the hub website itself can consume.

**Comment by flavio** [comment]
CC @ncounter - he's the author of the policy hub website.

**Comment by ncounter** [comment]
> CC @ncounter - he's the author of the policy hub website.

@flavio It makes sense to me. On the hub website side I could see it as a special checkbox filter where we suggest the user to

[ ] show only **must have**/**recommended** policies

or something like that. If the pool start exploding in the future, we could even think about two separate sections or tabs, one for the *essentials* and the other for the rest.

Btw, I'd not go ahead with the implementation on the UI side until the metadata flag (or whatever to differenciate the policies) is available so we know how many are on the total, and we know how we'd like the user to interact with them.

**Comment by viccuad** [comment]
> The goal is to have a page with a list of policies that we consider "a must" for our users.

Is "must" as in IETF "must" :)? If they need to present, I would prefer just packaging them on a helm chart, and adding the helm chart as a subchart of the present ones. This seems to tie with https://github.com/kubewarden/helm-charts/issues/52.

**Comment by flavio** [comment]
No, I meant something like "the editor's pick"

**Comment by jordojordo** [comment]
***Update***
Moving this to external blocked as the integration with Artifacthub will require a change within the backend of Rancher.

When attempting to fetch data from Artifacthub's api, Rancher will return a 502 gateway error ( [gist of the request](https://gist.github.com/jordojordo/8c418ee4f3f729b1b2d646c00ba79cc7) ). There issue is due to artifacthub.io not being whitelisted within Rancher.
There is a workaround if you change the `whitelist-domain` default setting in `management.cattle.io/v3/settings` from `forums.rancher.com` to `artifacthub.io`.

**Comment by jordojordo** [comment]
Closing this as https://github.com/kubewarden/ui/issues/211 has been completed which was the last step in showing a curated list of policies that are house on ArtifactHub.
